deck = [
    {
        "id": 1,
        "name": "Javascript",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 28,
            "avg_salary": 71457,
            "downloads": 12529489,
            "popularity": 15,
            "job_availability": 15,
        },
    },
    {
        "id": 2,
        "name": "Python",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 32,
            "avg_salary": 67500,
            "downloads": 90232242,
            "popularity": 20,
            "job_availability": 20,
        },
    },
    {
        "id": 3,
        "name": "Go",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 14,
            "avg_salary": 65000,
            "downloads": 9959490,
            "popularity": 12,
            "job_availability": 12,
        },
    },
    {
        "id": 4,
        "name": "Java",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 27,
            "avg_salary": 77091,
            "downloads": 20340247,
            "popularity": 17,
            "job_availability": 17,
        },
    },
    {
        "id": 5,
        "name": "Kotlin",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 13,
            "avg_salary": 41810,
            "downloads": 1042196,
            "popularity": 4,
            "job_availability": 4,
        },
    },
    {
        "id": 6,
        "name": "PHP",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 29,
            "avg_salary": 41830,
            "downloads": 9475496,
            "popularity": 14,
            "job_availability": 14,
        },
    },
    {
        "id": 7,
        "name": "CSharp",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 23,
            "avg_salary": 52500,
            "downloads": 22375966,
            "popularity": 16,
            "job_availability": 16,
        },
    },
    {
        "id": 8,
        "name": "Swift",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 9,
            "avg_salary": 60375,
            "downloads": 135064,
            "popularity": 9,
            "job_availability": 9,
        },
    },
    {
        "id": 9,
        "name": "Assembly",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 76,
            "avg_salary": 51931,
            "downloads": 606205,
            "popularity": 13,
            "job_availability": 13,
        },
    },
    {
        "id": 10,
        "name": "Ruby",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 28,
            "avg_salary": 70784,
            "downloads": 3365134,
            "popularity": 10,
            "job_availability": 10,
        },
    },
    {
        "id": 11,
        "name": "C",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 51,
            "avg_salary": 46550,
            "downloads": 25457435,
            "popularity": 19,
            "job_availability": 19,
        },
    },
    {
        "id": 12,
        "name": "COBOL",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 64,
            "avg_salary": 42842,
            "downloads": 50825,
            "popularity": 7,
            "job_availability": 7,
        },
    },
    {
        "id": 13,
        "name": "Fortran",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 66,
            "avg_salary": 47499,
            "downloads": 310454,
            "popularity": 11,
            "job_availability": 11,
        },
    },
    {
        "id": 14,
        "name": "Scala",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 19,
            "avg_salary": 47087,
            "downloads": 688777,
            "popularity": 2,
            "job_availability": 2,
        },
    },
    {
        "id": 15,
        "name": "C++",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 38,
            "avg_salary": 79475,
            "downloads": 23457435,
            "popularity": 18,
            "job_availability": 18,
        },
    },
    {
        "id": 16,
        "name": "OCaml",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 27,
            "avg_salary": 142500,
            "downloads": 107877,
            "popularity": 1,
            "job_availability": 1,
        },
    },
    {
        "id": 17,
        "name": "Lua",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 30,
            "avg_salary": 38000,
            "downloads": 850200,
            "popularity": 3,
            "job_availability": 3,
        },
    },
    {
        "id": 18,
        "name": "Julia",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 39,
            "avg_salary": 44345,
            "downloads": 537791,
            "popularity": 5,
            "job_availability": 5,
        },
    },
    {
        "id": 19,
        "name": "Rust",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 8,
            "avg_salary": 63606,
            "downloads": 1969477,
            "popularity": 8,
            "job_availability": 8,
        },
    },
    {
        "id": 20,
        "name": "Perl",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "stats": {
            "age": 35,
            "avg_salary": 46342,
            "downloads": 148867,
            "popularity": 6,
            "job_availability": 6,
        },
    },
]
